sudo: required

language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"

services:
  - docker

before_install:
  - docker pull crate:1.1.6
  - docker run -d -p 4200:4200 -p 4300:4300 crate:1.1.6

script:
  - npm test